# example k8s deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus-exporter
spec:
  selector:
    matchLabels:
      app: modbus-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: modbus-exporter
    spec:
      containers:
        - name: modbus-exporter
          image: stephanme/modbus_exporter:main
          imagePullPolicy: Always # for :main, remove when versioned
          ports:
            - containerPort: 9602
          command:
            - ./modbus_exporter
            - -config.file
            - /app/config/modbus.yml
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: modbus-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: modbus-exporter
spec:
  ports:
    - port: 9602
      targetPort: 9602
      name: metrics
  selector:
    app: modbus-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modbus-exporter-config
data:
  modbus.yml: |-
    modules:

        # Module name, needs to be passed as parameter by Prometheus.
      - name: "fake"
        protocol: 'tcp/ip'
        metrics:
            # Name of the metric.
          - name: "power_consumption_total"
            # Help text of the metric.
            help: "represents the overall power consumption by phase"
            # Labels to be added to the time series.
            labels:
              phase: "1"
            # Register address.
            address: 300022
            # Datatypes allowed: bool, int16, uint16, float16, float32
            dataType: int16
            # Endianness allowed: big, little, mixed, yolo
            # Optional. If not defined: big.
            endianness: big
            # Prometheus metric type: https://prometheus.io/docs/concepts/metric_types/.
            metricType: counter
            # Factor can be specified to represent metric value.
            # Examples: 1, 2, 1.543 etc
            # Optional.
            factor: 3.1415926535

          - name: "some_gauge"
            help: "some help for some gauge"
            address: 300023
            dataType: int16
            metricType: gauge
            factor: 2

          - name: "coil"
            help: "some help for some coil"
            address: 100024
            dataType: bool
            bitOffset: 0
            metricType: gauge
